# Serve locally with drafts (-D) and future-dated posts (-F) visible
default: serve

serve:
    hugo server -D -F

# Production build into public/
build:
    hugo --minify --cleanDestinationDir

# Scaffold a draft: just draft my-post-slug
draft name:
    hugo new posts/{{name}}.md

# Regenerate Chroma syntax highlighting for both color schemes
chroma:
    #!/usr/bin/env bash
    # Each sheet is scoped to its own prefers-color-scheme query rather than
    # layered light-then-dark, because the two Chroma styles do not emit the
    # same selector set: github emits .bp/.na/.nb/.p and github-dark does not,
    # so an unscoped light sheet would leak near-black punctuation into dark.
    #
    # The strip removes only the wrapper's own colors, leaving the site-wide
    # `pre` tint in main.css to supply the background. The token backgrounds on
    # .err, .hl, .gd and .gi are meaningful and must survive.
    set -euo pipefail
    gen() {
      echo "/* GENERATED by \`just chroma\` from --style=$1. Do not edit by hand. */"
      echo "@media (prefers-color-scheme: $2) {"
      hugo gen chromastyles --style="$1" \
        | sed -e '/^\/\* Background \*\//d' -e '/PreWrapper/s/[a-z-]*color:#[0-9a-f]*;//g'
      echo "}"
    }
    gen github      light > assets/css/chroma.css
    gen github-dark dark  > assets/css/chroma-dark.css
